name: Feature Request 🚀
description: Suggest a new feature or improvement
labels: ["enhancement","hard","IWOC2024"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help everyone identify the new feature or improvement
  - type: textarea
    id: description
    attributes:
      label: Describe your improvement idea or feature request
      placeholder: A clear and concise description of what the idea or feature is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: How would you like to see it implemented?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See improvement
    validations:
      required: true
 

  - type: textarea
    id: contact
    attributes:
      label: How can we contact you (optional)
      placeholder: |
        Leave your discord or social media handle
    validations:
      required: false
  - type: dropdown
    id: assign
    attributes:
      label: "Would you like to work on this issue?"
      options:
        - "Yes"
        - "No"
  - type: checkboxes
    id: terms
    attributes:
      label: "By submitting this issue, I have confirmed that:"
      options:
        - label: I have starred the repo ⭐
          required: true
        
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this issue! We will get back to you as soon as possible.